sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: asdfghjkl123
  redis:
    host: 
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: 
    secret: 
  shop:
    address: 北京市海淀区上地十街10号
  gaode:
    key: 
